#!/usr/bin/env bash

# This is file is require by gradescope.
# This is the start of the autograder.

# start up database for testing.
#   (may move to its own file later)
su - postgres -c 'pg_ctlcluster 18 main start'
su - postgres -c "psql -U postgres -f /autograder/source/$DB_USER_SET"

if [ "$DB_BUILD" != "" ]; then
    pg_restore -U testee -h localhost -d testee -O /autograder/source/"$DB_BUILD"
fi

if [ "$PRIV_SET" != "" ]; then
    psql -U testee -h localhost -d testee -f /autograder/source/"$PRIV_SET"
fi

# move assignment file into source so it is accessible by run_test
cp /autograder/submission/"$HW_NAME" /autograder/source/"$HW_NAME"

# create unpriviliged user
useradd -m -s /bin/bash pte
mv /root/.pgpass /home/pte/.pgpass
chown pte:pte /home/pte/.pgpass
chown pte:pte $HW_NAME
chown pte:pte $GOLD_FILE

 
# run testing script
sudo --preserve-env=DB_USER,DB_NAME,HW_NAME,GOLD_FILE,SOL_NUM -u pte HOME=/home/pte python3 run_test.py