#!/usr/bin/env bash

# This is file is require by gradescope.
# This is the start of the autograder.

# start up database for testing.
#   (may move to its own file later)
su - postgres -c 'pg_ctlcluster 18 main start'
su - postgres -c "psql -U postgres -f /autograder/source/$DB_SETUP"
pg_restore -U testee -h localhost -d testee -O /autograder/source/"$DB_BUILD"

# move assignment file into source so it is accessible by run_test
cp /autograder/submission/"$HW_NAME" /autograder/source/"$HW_NAME"

# move into appropriate directory for testing
cd /autograder/source

# run testing script
python3 run_test.py