#!/usr/bin/env bash

su - postgres -c 'pg_ctlcluster 18 main start'
su - postgres -c 'psql -U postgres -f /autograder/source/dbset.sql'

cp /autograder/submission/many.sql /autograder/source/many.sql

cd /autograder/source

python3 run_test.py